# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38690d484326624b5cf86a72a94e2016"
name = "wish"
application_url = "https://69d2f5bfa4ee.ngrok-free.app"
embedded = true
handle = "wish-35"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders"

[auth]
redirect_urls = ["https://69d2f5bfa4ee.ngrok-free.app/auth/callback", "https://69d2f5bfa4ee.ngrok-free.app/auth/shopify/callback", "https://69d2f5bfa4ee.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
